# Generated by Django 4.1.1 on 2022-10-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text="Choose a title for your artwork. It can't be longer than 150 characters and is unique.", max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text="Describe your artwork in your own words. What are your thoughts and what's the intention behind your masterpiece.", null=True)),
                ('type', models.CharField(choices=[('Painting', 'Painting'), ('Drawing', 'Drawing'), ('Sculpture', 'Sculpture'), ('Architecture', 'Architecture'), ('Literature', 'Literature'), ('Music', 'Music'), ('Theater', 'Theater'), ('Dance', 'Dance'), ('Cinema', 'Cinema')], help_text='Choose your type of art.', max_length=150)),
                ('file', models.FileField(upload_to='')),
                ('is_stage', models.BooleanField(default=True)),
                ('is_showroom', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_artist', models.BooleanField(default=False)),
                ('is_enthusiast', models.BooleanField(default=True)),
                ('is_collaborator', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_artist', models.BooleanField(default=False)),
                ('is_enthusiast', models.BooleanField(default=True)),
                ('is_collaborator', models.BooleanField(default=False)),
                ('comment', models.TextField(help_text='Share your toughts.', null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
