# Generated by Django 4.1.2 on 2022-10-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Share your toughts.', null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text="Describe your artwork in your own words. What are your thoughts and what's the intention behind your masterpiece.", null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='artworks/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text="Choose a title for your artwork. It can't be longer than 150 characters and is unique.", max_length=150, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Drawing', 'Drawing'), ('Sculpture', 'Sculpture'), ('Architecture', 'Architecture'), ('Literature', 'Literature'), ('Music', 'Music'), ('Theater', 'Theater'), ('Dance', 'Dance'), ('Cinema', 'Cinema')], help_text='Choose your type of art.', max_length=150, verbose_name='type'),
        ),
    ]
