# Generated by Django 4.1.3 on 2022-12-08 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0002_remove_post_type_post_art_type_alter_post_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='art_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
