# Generated by Django 4.1.3 on 2022-12-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload your avatar.', null=True, upload_to='artworks/avatars/%Y/%m/%d/'),
        ),
    ]
